/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ventanas;

import modelos.Usuario;

/**
 *
 * @author yendri
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private Usuario UsuarioActivo;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal(Usuario usuarioActivo) {
        initComponents();
        UsuarioActivo = usuarioActivo;
        CargarInterfaz();
    }

    private void CargarInterfaz() {
        jlUsuarioActivo.setText(UsuarioActivo.getUsuario());

        if (UsuarioActivo.getRol().getId() == 1) { // Admin

        }

        if (UsuarioActivo.getRol().getId() == 2) { // Mesero
            btnPlatos.setEnabled(false);
            btnUsuarios.setEnabled(false);
            btnAjustes.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        PANELinicio = new javax.swing.JDesktopPane();
        jpcontrolador = new javax.swing.JPanel();
        btnPlatos = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnAjustes = new javax.swing.JButton();
        lbllogo = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        jlUsuarioActivo = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        jpventanas = new javax.swing.JTabbedPane();
        jpInicio = new javax.swing.JTabbedPane();
        jpMesas = new javax.swing.JPanel();
        jpRegistro = new javax.swing.JPanel();
        jpNosotros = new javax.swing.JPanel();
        jpDatos = new javax.swing.JPanel();
        jpdatos1 = new javax.swing.JPanel();
        lblnombreempresa = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lblredes = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        lblmensaje = new javax.swing.JLabel();
        lblmensaje1 = new javax.swing.JLabel();
        lblmensaje2 = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        lblnombre2 = new javax.swing.JLabel();
        lbldireccio1 = new javax.swing.JLabel();
        lbldireccion2 = new javax.swing.JLabel();
        lblfb = new javax.swing.JLabel();
        lblinstagram = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbldatos = new javax.swing.JLabel();
        jpSalir = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlatos.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        btnPlatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_platos.png"))); // NOI18N
        btnPlatos.setText("Platos");
        btnPlatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlatosMouseClicked(evt);
            }
        });
        btnPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatosActionPerformed(evt);
            }
        });

        btnMesas.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        btnMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_mesas.png"))); // NOI18N
        btnMesas.setText("Mesas");
        btnMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMesasMouseClicked(evt);
            }
        });

        btnPedidos.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_pedidos.png"))); // NOI18N
        btnPedidos.setText("Pedidos");

        btnAjustes.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_ajustes.png"))); // NOI18N
        btnAjustes.setText("Ajustes");

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imagen_menu_principal.png"))); // NOI18N
        lbllogo.setText("LOGO");

        btnUsuarios.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_usuarios.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });

        jlUsuarioActivo.setFont(new java.awt.Font("Gargi", 1, 18)); // NOI18N
        jlUsuarioActivo.setText("-");

        javax.swing.GroupLayout jpcontroladorLayout = new javax.swing.GroupLayout(jpcontrolador);
        jpcontrolador.setLayout(jpcontroladorLayout);
        jpcontroladorLayout.setHorizontalGroup(
            jpcontroladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcontroladorLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jpcontroladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpcontroladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addComponent(btnPedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbllogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpcontroladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addComponent(jlUsuarioActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpcontroladorLayout.setVerticalGroup(
            jpcontroladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcontroladorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jlUsuarioActivo)
                .addGap(20, 20, 20))
        );

        PANELinicio.add(jpcontrolador);
        jpcontrolador.setBounds(0, 0, 250, 700);

        lblnombre.setBackground(new java.awt.Color(0, 204, 204));
        lblnombre.setFont(new java.awt.Font("Goudy Old Style", 0, 48)); // NOI18N
        lblnombre.setText("La Tortilleria CR");
        PANELinicio.add(lblnombre);
        lblnombre.setBounds(540, 10, 440, 50);

        jpventanas.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N

        jpInicio.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        jpventanas.addTab("Pagina Principal", jpInicio);

        javax.swing.GroupLayout jpMesasLayout = new javax.swing.GroupLayout(jpMesas);
        jpMesas.setLayout(jpMesasLayout);
        jpMesasLayout.setHorizontalGroup(
            jpMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jpMesasLayout.setVerticalGroup(
            jpMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        jpventanas.addTab("Mesas del Salon", jpMesas);

        javax.swing.GroupLayout jpRegistroLayout = new javax.swing.GroupLayout(jpRegistro);
        jpRegistro.setLayout(jpRegistroLayout);
        jpRegistroLayout.setHorizontalGroup(
            jpRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jpRegistroLayout.setVerticalGroup(
            jpRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        jpventanas.addTab("Registro de Pedidos", jpRegistro);

        lblnombreempresa.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lblnombreempresa.setText("Nombre de Nuestra Empresa:");

        lbltelefono.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbltelefono.setText("Telefono:");

        lblredes.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lblredes.setText("Redes Sociales:");

        lbldireccion.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lbldireccion.setText("Direccion:");

        lblmensaje.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        lblmensaje.setText("Mensaje a Nuestros Clientes:");

        lblmensaje1.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        lblmensaje1.setText("\"La calidad en un producto, o servicio no es lo ");

        lblmensaje2.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        lblmensaje2.setText("que tu le pones, sino lo que el cliente obtiene\"");

        lblnumero.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        lblnumero.setText("2230-3768");

        lblnombre2.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        lblnombre2.setText("La Tortilleria CR");

        lbldireccio1.setFont(new java.awt.Font("Goudy Old Style", 0, 20)); // NOI18N
        lbldireccio1.setText("WWPJ+6FW 1447-1002, C. 23 1447-1002, ");

        lbldireccion2.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        lbldireccion2.setText("Aranjuez, San José, 10101");

        lblfb.setFont(new java.awt.Font("Goudy Old Style", 0, 20)); // NOI18N
        lblfb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_facebook.png"))); // NOI18N
        lblfb.setText("Facebook");

        lblinstagram.setFont(new java.awt.Font("Goudy Old Style", 0, 20)); // NOI18N
        lblinstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_instagram.png"))); // NOI18N
        lblinstagram.setText("Instagram");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imagen_datos_empresa.jpg"))); // NOI18N

        javax.swing.GroupLayout jpdatos1Layout = new javax.swing.GroupLayout(jpdatos1);
        jpdatos1.setLayout(jpdatos1Layout);
        jpdatos1Layout.setHorizontalGroup(
            jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdatos1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpdatos1Layout.createSequentialGroup()
                        .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbldireccio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbldireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblnombre2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblnombreempresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbldireccion2))
                        .addGap(28, 28, 28)
                        .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpdatos1Layout.createSequentialGroup()
                                .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblredes, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(lblnumero))
                                .addGap(306, 306, 306))
                            .addGroup(jpdatos1Layout.createSequentialGroup()
                                .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblfb)
                                    .addGroup(jpdatos1Layout.createSequentialGroup()
                                        .addComponent(lblinstagram)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpdatos1Layout.createSequentialGroup()
                        .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpdatos1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(lblmensaje))
                            .addGroup(jpdatos1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblmensaje2))
                            .addComponent(lblmensaje1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpdatos1Layout.setVerticalGroup(
            jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdatos1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombreempresa)
                    .addComponent(lbltelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnumero)
                    .addComponent(lblnombre2))
                .addGap(27, 27, 27)
                .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblredes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldireccio1)
                    .addComponent(lblfb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpdatos1Layout.createSequentialGroup()
                        .addGroup(jpdatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldireccion2)
                            .addComponent(lblinstagram))
                        .addGap(54, 54, 54)
                        .addComponent(lblmensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblmensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmensaje2))
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbldatos.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        lbldatos.setText("DATOS DE LA EMPRESA");

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(lbldatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpdatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbldatos)
                .addGap(18, 18, 18)
                .addComponent(jpdatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpNosotrosLayout = new javax.swing.GroupLayout(jpNosotros);
        jpNosotros.setLayout(jpNosotrosLayout);
        jpNosotrosLayout.setHorizontalGroup(
            jpNosotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNosotrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpNosotrosLayout.setVerticalGroup(
            jpNosotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNosotrosLayout.createSequentialGroup()
                .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpventanas.addTab("Sobre Nosotros", jpNosotros);

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpSalirLayout = new javax.swing.GroupLayout(jpSalir);
        jpSalir.setLayout(jpSalirLayout);
        jpSalirLayout.setHorizontalGroup(
            jpSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSalirLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnCerrarSesion)
                .addContainerGap(758, Short.MAX_VALUE))
        );
        jpSalirLayout.setVerticalGroup(
            jpSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSalirLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnCerrarSesion)
                .addContainerGap(519, Short.MAX_VALUE))
        );

        jpventanas.addTab("Salir", jpSalir);

        PANELinicio.add(jpventanas);
        jpventanas.setBounds(260, 90, 900, 600);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        PANELinicio.add(jPanel5);
        jPanel5.setBounds(260, 120, 890, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANELinicio, javax.swing.GroupLayout.DEFAULT_SIZE, 1157, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANELinicio, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        //
        // Guardar en archivos antes de salir 
        //

        FrmLogin ventana = new FrmLogin();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        FrmUsuarios ventana = new FrmUsuarios(UsuarioActivo);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void btnMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesasMouseClicked
        FrmMesas ventana = new FrmMesas(UsuarioActivo);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMesasMouseClicked

    private void btnPlatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlatosMouseClicked
        FrmPlatos ventana = new FrmPlatos(UsuarioActivo);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlatosMouseClicked

    private void btnPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PANELinicio;
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnPlatos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jlUsuarioActivo;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JTabbedPane jpInicio;
    private javax.swing.JPanel jpMesas;
    private javax.swing.JPanel jpNosotros;
    private javax.swing.JPanel jpRegistro;
    private javax.swing.JPanel jpSalir;
    private javax.swing.JPanel jpcontrolador;
    private javax.swing.JPanel jpdatos1;
    private javax.swing.JTabbedPane jpventanas;
    private javax.swing.JLabel lbldatos;
    private javax.swing.JLabel lbldireccio1;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lbldireccion2;
    private javax.swing.JLabel lblfb;
    private javax.swing.JLabel lblinstagram;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lblmensaje;
    private javax.swing.JLabel lblmensaje1;
    private javax.swing.JLabel lblmensaje2;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombre2;
    private javax.swing.JLabel lblnombreempresa;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lblredes;
    private javax.swing.JLabel lbltelefono;
    // End of variables declaration//GEN-END:variables

}
