/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.LogicaMesas;
import modelos.Mesa;
import modelos.Usuario;

/**
 *
 * @author yendri
 */
public class FrmMesas extends javax.swing.JFrame {

    private Usuario UsuarioActivo;
    private LinkedList<Mesa> lista_mesas;
    private LogicaMesas l_mesas;

    private boolean Creando;
    private boolean Editando;

    /**
     * Creates new form FrmUsuarios
     */
    public FrmMesas(Usuario usuarioActivo) {
        initComponents();
        UsuarioActivo = usuarioActivo;

        // Intancias de las clases que contienen la logica de negocio
        l_mesas = new LogicaMesas();

        // Cargas de información
        CargarMesas();
        CargarInterfaz();
    }

    private void CargarInterfaz() {
        CambiarEstadoControles(false);
    }

    /**
     * Metodo que modifica la interfaz segun se requiere habilada o inhabilitada
     */
    private void CambiarEstadoControles(boolean estado) {
        txtNumero.setEnabled(false);
        txtPersonas.setEnabled(estado);
        btnGuardar.setEnabled(estado);
        btnCancelar.setEnabled(estado);
        txtNumero.setText("");
        txtPersonas.setText("");
    }

    // Busca el id más alto en la lista y le suma 1 para evitar que se repita
    private Mesa IdMasAlto() {
        Mesa mesaConMayorID = null;
        int maxID = Integer.MIN_VALUE;

        for (Mesa m : lista_mesas) {
            if (m.getNumero() > maxID) {
                maxID = m.getNumero();
                mesaConMayorID = m;
            }
        }

        return mesaConMayorID;
    }

    // carga la lista de usuarios en el jtable
    private void CargarMesas() {
        lista_mesas = l_mesas.getListaMesas();

        // Definir los nombres de las columnas
        String[] columnas = {"Numero", "Cantidad de Personas"};

        // Crear un DefaultTableModel con las columnas vacías y 0 filas
        DefaultTableModel model = new DefaultTableModel(columnas, 0);

        // Llenar el modelo con los datos de la lista de usuarios
        for (Mesa m : lista_mesas) {
            Object[] rowData = {m.getNumero(), m.getNumero_personas()};
            model.addRow(rowData);
        }

        jtMesas.setModel(model);
    }

    // carga los datos del usuario seleccionado en la tabla en los respectivos inputs
    private void CargarDatos(Mesa seleccionado) {
        txtNumero.setText(String.valueOf(seleccionado.getNumero()));
        txtPersonas.setText(String.valueOf(seleccionado.getNumero_personas()));
    }

    private void GuardarMesa(Mesa m) {
        l_mesas.guardarMesa(m);
        CambiarEstadoControles(false);
        btnCrear.setEnabled(true);
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
        CargarMesas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtMesas = new javax.swing.JTable();
        jlTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtPersonas = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtMesas);

        jlTitle.setText("Gestion Mesas");

        lblNumero.setText("Numero");

        lblUsuario.setText("Cantidad de Personas");

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        btnCrear.setText("Crear Nueva");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitle)
                .addGap(346, 346, 346))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnEditar)
                    .addComponent(btnCrear)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        FrmMenuPrincipal ventana = new FrmMenuPrincipal(UsuarioActivo);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        if (btnCrear.isEnabled()) {
            Editando = false;
            Creando = true;
            CambiarEstadoControles(true);
            int id_nuevo = IdMasAlto().getNumero() + 1;
            txtNumero.setText(String.valueOf(id_nuevo));
            btnCrear.setEnabled(false);
            btnEditar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if (btnCancelar.isEnabled()) {
            CambiarEstadoControles(false);
            btnCrear.setEnabled(true);
            btnEditar.setEnabled(true);
            btnEliminar.setEnabled(true);
            Editando = false;
            Creando = false;
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        if (btnEditar.isEnabled()) {
            Editando = true;
            Creando = false;
            int filaSeleccionada = jtMesas.getSelectedRow();

            // verficia si hay una linea seleccionada en la tabla
            if (filaSeleccionada != -1) {
                int numero = (int) jtMesas.getModel().getValueAt(filaSeleccionada, 0);;
                Mesa seleccionado = l_mesas.buscarPorNumero(numero);
                CambiarEstadoControles(true);
                CargarDatos(seleccionado);
                btnCrear.setEnabled(false);
                btnEditar.setEnabled(false);
                btnEliminar.setEnabled(false);
            } else {
                // Si no hay fila seleccionada
                // Realiza la lógica que quieras ejecutar cuando no haya nada seleccionado
                JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada", "Atención", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if (btnGuardar.isEnabled()) {
            Mesa m = new Mesa();
            m.setNumero(Integer.parseInt(txtNumero.getText().trim()));
            m.setNumero_personas(Integer.parseInt(txtPersonas.getText().trim()));

            if (Creando) {
                if (l_mesas.buscarPorNumero(m.getNumero()) == null) {
                    GuardarMesa(m);
                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe este numero de mesa en el sistema", "Atención", JOptionPane.WARNING_MESSAGE);
                }
            } else if (Editando) {
                GuardarMesa(m);
            } else {

            }
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (btnEliminar.isEnabled()) {
            int filaSeleccionada = jtMesas.getSelectedRow();

            if (filaSeleccionada != -1) {
                int numero = (int) jtMesas.getModel().getValueAt(filaSeleccionada, 0);;
                Mesa seleccionado = l_mesas.buscarPorNumero(numero);

                l_mesas.eliminarMesa(seleccionado);

                CargarMesas();

            } else {
                // Si no hay fila seleccionada
                // Realiza la lógica que quieras ejecutar cuando no haya nada seleccionado
                JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada", "Atención", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JTable jtMesas;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPersonas;
    // End of variables declaration//GEN-END:variables
}
