/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.LogicaCategorias;
import logica.LogicaPlatos;
import modelos.Categoria;
import modelos.Plato;
import modelos.Usuario;

/**
 *
 * @author yendri
 */
public class FrmPlatos extends javax.swing.JFrame {

    private Usuario UsuarioActivo;
    private LinkedList<Plato> lista_platos;
    private LinkedList<Categoria> lista_categorias;
    private LogicaPlatos l_platos;
    private LogicaCategorias l_categorias;

    private boolean Creando;
    private boolean Editando;

    /**
     * Creates new form FrmUsuarios
     */
    public FrmPlatos(Usuario usuarioActivo) {
        initComponents();
        UsuarioActivo = usuarioActivo;

        // Intancias de las clases que contienen la logica de negocio
        l_platos = new LogicaPlatos();
        l_categorias = new LogicaCategorias();
        lista_categorias = l_categorias.getListaCategorias();
        // Cargas de información
        CargarPlatos();
        CargarInterfaz();
        CargarCategorias();
    }

    private void CargarInterfaz() {
        CambiarEstadoControles(false);
    }

    private void CargarCategorias() {
        // Agregar elementos al JComboBox
        for (Categoria c : lista_categorias) {
            jcbCategoria.addItem(c.getNombre());
        }
    }

    /**
     * Metodo que modifica la interfaz segun se requiere habilada o inhabilitada
     */
    private void CambiarEstadoControles(boolean estado) {
        txtCodigo.setEnabled(estado);
        txtNombre.setEnabled(estado);
        txtDescripcion.setEnabled(estado);
        txtPrecio.setEnabled(estado);
        jcbCategoria.setEnabled(estado);
        btnGuardar.setEnabled(estado);
        btnCancelar.setEnabled(estado);
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        jcbCategoria.setSelectedItem("Entrada");
    }

    // carga la lista de usuarios en el jtable
    private void CargarPlatos() {
        lista_platos = l_platos.getListaPlatos();

        // Definir los nombres de las columnas
        String[] columnas = {"Codigo", "Nombre", "Descripción", "Precio", "Categoria"};

        // Crear un DefaultTableModel con las columnas vacías y 0 filas
        DefaultTableModel model = new DefaultTableModel(columnas, 0);

        // Llenar el modelo con los datos de la lista de usuarios
        for (Plato p : lista_platos) {
            // acá se muestra el valor ajustado de la descripción sin enters pero sin & cambiandolo por ". " para mostrar correctamente la tabla
            Object[] rowData = {p.getCodigo(), p.getNombre(), p.getDescripcion().replace("&", ". "), p.getPrecio(), l_categorias.buscarPorId(p.getCategoria()).getNombre()};
            model.addRow(rowData);
        }

        jtPlatos.setModel(model);
    }

    // carga los datos del usuario seleccionado en la tabla en los respectivos inputs
    private void CargarDatos(Plato seleccionado) {
        txtCodigo.setText(String.valueOf(seleccionado.getCodigo()));
        txtNombre.setText(seleccionado.getNombre());
        // acá se muestra el valor original de la descripcion reemplazando los & por el respetivo enter
        txtDescripcion.setText(seleccionado.getDescripcion().replace("&", "\n"));
        txtPrecio.setText(String.valueOf(seleccionado.getPrecio()));
        jcbCategoria.setSelectedItem(l_categorias.buscarPorId(seleccionado.getCategoria()).getNombre());
    }

    private void GuardarPlato(Plato p) {
        l_platos.guardarPlato(p);
        CambiarEstadoControles(false);
        btnCrear.setEnabled(true);
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnVerDescripcion.setEnabled(true);
        CargarPlatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPlatos = new javax.swing.JTable();
        jlTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        jcbCategoria = new javax.swing.JComboBox<>();
        lblCategoria = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnVolver = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVerDescripcion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtPlatos);

        jlTitle.setText("Gestion Platos");

        lblCodigo.setText("Codigo");

        lblNombre.setText("Nombre");

        lblDescripcion.setText("Descripcion");

        lblPrecio.setText("Precio");

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        lblCategoria.setText("Categoria");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescripcion)
                    .addComponent(lblPrecio)
                    .addComponent(jcbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar))
                    .addComponent(lblCategoria)
                    .addComponent(txtPrecio)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        btnCrear.setText("Crear Nuevo");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnVerDescripcion.setText("Ver Descripcion");
        btnVerDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerDescripcionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitle)
                .addGap(348, 348, 348))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnCrear)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnVerDescripcion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        FrmMenuPrincipal ventana = new FrmMenuPrincipal(UsuarioActivo);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        if (btnCrear.isEnabled()) {
            Editando = false;
            Creando = true;
            CambiarEstadoControles(true);
            btnCrear.setEnabled(false);
            btnEditar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnVerDescripcion.setEnabled(false);
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if (btnCancelar.isEnabled()) {
            CambiarEstadoControles(false);
            btnCrear.setEnabled(true);
            btnEditar.setEnabled(true);
            btnEliminar.setEnabled(true);
            btnVerDescripcion.setEnabled(true);
            Editando = false;
            Creando = false;
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        if (btnEditar.isEnabled()) {
            Editando = true;
            Creando = false;
            int filaSeleccionada = jtPlatos.getSelectedRow();

            // verficia si hay una linea seleccionada en la tabla
            if (filaSeleccionada != -1) {
                String codigo = (String) jtPlatos.getModel().getValueAt(filaSeleccionada, 0);
                Plato seleccionado = l_platos.buscarPorCodigo(codigo);
                CambiarEstadoControles(true);
                CargarDatos(seleccionado);
                btnCrear.setEnabled(false);
                btnEditar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnVerDescripcion.setEnabled(false);
            } else {
                // Si no hay fila seleccionada
                // Realiza la lógica que quieras ejecutar cuando no haya nada seleccionado
                JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada", "Atención", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if (btnGuardar.isEnabled()) {
            Plato p = new Plato();
            p.setCodigo(txtCodigo.getText().trim());
            p.setNombre(txtNombre.getText().trim());
            p.setDescripcion(txtDescripcion.getText().trim());
            p.setPrecio(Double.parseDouble(txtPrecio.getText().trim()));
            p.setCategoria(l_categorias.buscarPorNombre(jcbCategoria.getSelectedItem().toString()).getId());

            if (Creando) {
                if (l_platos.buscarPorCodigo(p.getCodigo()) == null) {
                    GuardarPlato(p);
                } else {
                    JOptionPane.showMessageDialog(this, "Ya existe este codigo en el sistema", "Atención", JOptionPane.WARNING_MESSAGE);
                }
            } else if (Editando) {
                GuardarPlato(p);
            } else {

            }
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (btnEliminar.isEnabled()) {
            int filaSeleccionada = jtPlatos.getSelectedRow();

            if (filaSeleccionada != -1) {
                String codigo = (String) jtPlatos.getModel().getValueAt(filaSeleccionada, 0);
                Plato seleccionado = l_platos.buscarPorCodigo(codigo);

                l_platos.eliminarPlato(seleccionado);
                CargarPlatos();
            } else {
                // Si no hay fila seleccionada
                // Realiza la lógica que quieras ejecutar cuando no haya nada seleccionado
                JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada", "Atención", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnVerDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerDescripcionMouseClicked
        if (btnVerDescripcion.isEnabled()) {
            int filaSeleccionada = jtPlatos.getSelectedRow();

            if (filaSeleccionada != -1) {
                String codigo = (String) jtPlatos.getModel().getValueAt(filaSeleccionada, 0);

                // acá se muestra el valor original de la descripcion reemplazando los & por el respetivo enter
                JOptionPane.showMessageDialog(this, l_platos.buscarPorCodigo(codigo).getDescripcion().replace("&", "\n"), "Descripción", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Si no hay fila seleccionada
                // Realiza la lógica que quieras ejecutar cuando no haya nada seleccionado
                JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada", "Atención", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnVerDescripcionMouseClicked

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerDescripcion;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JTable jtPlatos;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
