/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.LogicaArchivos;
import logica.LogicaRoles;
import logica.LogicaUsuarios;
import modelos.Rol;
import modelos.Usuario;

/**
 *
 * @author yendri
 */
public class FrmUsuarios extends javax.swing.JFrame {

    private Usuario UsuarioActivo;
    private LinkedList<Usuario> lista_usuarios;
    private LinkedList<Rol> lista_roles;
    private LogicaUsuarios l_usuarios;
    private LogicaRoles l_roles;
    private LogicaArchivos l_archivos;

    /**
     * Creates new form FrmUsuarios
     */
    public FrmUsuarios(Usuario usuarioActivo) {
        initComponents();
        UsuarioActivo = usuarioActivo;

        // Intancias de las clases que contienen la logica de negocio
        l_usuarios = new LogicaUsuarios();
        l_roles = new LogicaRoles();
        lista_roles = l_roles.getListaRoles();

        // Cargas de información
        CargarUsuarios();
        CargarInterfaz();
        CargarRoles();
    }

    private void CargarInterfaz() {
        CambiarEstadoControles(false);
    }

    /**
     * Metodo que modifica la interfaz segun se requiere habilada o inhabilitada
     */
    private void CambiarEstadoControles(boolean estado) {
        txtID.setEnabled(false);
        txtUsuario.setEnabled(estado);
        jfielPassword.setEnabled(estado);
        jcbRoles.setEnabled(estado);
        btnGuardar.setEnabled(estado);
        btnCancelar.setEnabled(estado);
        txtID.setText("");
        txtUsuario.setText("");
        jfielPassword.setText("");
        jcbRoles.setSelectedItem("Administrador");
    }

    // Busca el id más alto en la lista y le suma 1 para evitar que se repita
    private Usuario IdMasAlto() {
        Usuario usuarioConMayorID = null;
        int maxID = Integer.MIN_VALUE;

        for (Usuario usuario : lista_usuarios) {
            if (usuario.getId() > maxID) {
                maxID = usuario.getId();
                usuarioConMayorID = usuario;
            }
        }

        return usuarioConMayorID;
    }

    // carga la lista de usuarios en el jtable
    private void CargarUsuarios() {
        lista_usuarios = l_usuarios.getListaUsuarios();

        // Definir los nombres de las columnas
        String[] columnas = {"ID", "Usuario", "Rol"};

        // Crear un DefaultTableModel con las columnas vacías y 0 filas
        DefaultTableModel model = new DefaultTableModel(columnas, 0);

        // Llenar el modelo con los datos de la lista de usuarios
        for (Usuario usuario : lista_usuarios) {
            Object[] rowData = {usuario.getId(), usuario.getUsuario(), usuario.getRol().getNombre()};
            model.addRow(rowData);
        }

        jtUsuarios.setModel(model);
    }

    // carga la lista de roles en el combobox
    private void CargarRoles() {
        // Agregar elementos al JComboBox
        for (Rol r : lista_roles) {
            jcbRoles.addItem(r.getNombre());
        }
    }

    // carga los datos del usuario seleccionado en la tabla en los respectivos inputs
    private void CargarDatos(Usuario seleccionado) {
        txtID.setText(String.valueOf(seleccionado.getId()));
        txtUsuario.setText(seleccionado.getUsuario());
        jfielPassword.setText(seleccionado.getContrasena());
        jcbRoles.setSelectedItem(seleccionado.getRol().getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        jlTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jcbRoles = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jfielPassword = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtUsuarios);

        jlTitle.setText("Gestion Usuarios");

        lblID.setText("ID");

        lblUsuario.setText("Usuario");

        lblContrasena.setText("Contraseña");

        lblRol.setText("Rol");

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jfielPassword)
                        .addComponent(lblID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(lblContrasena, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblRol, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jcbRoles, 0, 187, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfielPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        btnCrear.setText("Crear Nuevo");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitle)
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnEditar)
                    .addComponent(btnCrear)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        FrmMenuPrincipal ventana = new FrmMenuPrincipal(UsuarioActivo);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        CambiarEstadoControles(true);
        int id_nuevo = IdMasAlto().getId() + 1;
        txtID.setText(String.valueOf(id_nuevo));
        btnCrear.setEnabled(false);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        CambiarEstadoControles(false);
        btnCrear.setEnabled(true);
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        int filaSeleccionada = jtUsuarios.getSelectedRow();
        
        // verficia si hay una linea seleccionada en la tabla
        if (filaSeleccionada != -1) {
            int id = (int) jtUsuarios.getModel().getValueAt(filaSeleccionada, 0);;
            Usuario seleccionado = l_usuarios.buscarPorId(id);
            CambiarEstadoControles(true);
            CargarDatos(seleccionado);
            btnCrear.setEnabled(false);
            btnEditar.setEnabled(false);
            btnEliminar.setEnabled(false);
        } else {
            // Si no hay fila seleccionada
            // Realiza la lógica que quieras ejecutar cuando no haya nada seleccionado
            JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada");
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        Usuario u = new Usuario();
        u.setId(Integer.parseInt(txtID.getText()));
        u.setUsuario(txtUsuario.getText().trim());
        u.setContrasena(new String(jfielPassword.getPassword()));
        u.setRol(l_roles.buscarPorNombre(jcbRoles.getSelectedItem().toString()));

        l_usuarios.guardarUsuario(u);
        CambiarEstadoControles(false);
        btnCrear.setEnabled(true);
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
        CargarUsuarios();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int filaSeleccionada = jtUsuarios.getSelectedRow();

        if (filaSeleccionada != -1) {
            int id = (int) jtUsuarios.getModel().getValueAt(filaSeleccionada, 0);;
            Usuario seleccionado = l_usuarios.buscarPorId(id);

            l_usuarios.eliminarUsuario(seleccionado);

            CargarUsuarios();

        } else {
            // Si no hay fila seleccionada
            // Realiza la lógica que quieras ejecutar cuando no haya nada seleccionado
            JOptionPane.showMessageDialog(this, "No hay ninguna fila seleccionada");
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbRoles;
    private javax.swing.JPasswordField jfielPassword;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JTable jtUsuarios;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
